### ISSUE TITLE
Update to support current LLVM/Clang

### ISSUE THREAD

**Issue by LorenDB** [Superbelko/ohmygentool#18]
As a user of a rolling distro (openSUSE Tumbleweed), I'd love to be able to build this without having to downgrade packages, but apparently LLVM 13 has breaking API changes. Is this something that could be fixed?

**Comment by Superbelko** [comment]
Yes, I'll look into it probably next week. Sorry, quite tight schedule a.t.m.
For now you can probably use docker image.

**Comment by LorenDB** [comment]
OK, I'll check out the docker image. I did quickly hack together something that builds (I haven't tested whether it works yet, though). I'll fork and push later today if you want to check it out.

**Comment by LorenDB** [comment]
My changes are now at https://github.com/LorenDB/ohmygentool

**Comment by Superbelko** [comment]
Thank you for contributing. 
I'll fix older versions later.

**Comment by LorenDB** [comment]
Again, I want to make clear that want I have up on my fork is merely a commit that builds with latest clang/llvm. I do not know whether it actually generates proper code or not.

**Comment by Superbelko** [comment]
Yes, thanks anyway. I have clean machine so I need to build clang again. 
I'll fix it if it's broken, but guessing from the changes it should work.

**Comment by LorenDB** [comment]
The part I'm most concerned about is the template size of 20 on the SmallStrings. I'm not sure if that will affect anything or not, but it might be a good idea to test that part specifically.
