### ISSUE TITLE
Error when generating enums

### ISSUE THREAD

**Issue by Imperatorn** [Superbelko/ohmygentool#9]
When generating enums, there's a small issue if the character used is backtick, since it's used for the value.

enum ACS_DIAMOND = `PDC_ACS('`')` <--This would not be handled properly. You would get "unterminated character constant"

**Comment by Superbelko** [comment]
In C++ or in D? 
Sorry I don't get it, formatting destroyed it. 
Can you attach screenshot of what the source and the result?

**Comment by Superbelko** [comment]
Minimal repro case

```c
#define NOOP(a) a
#define BUG NOOP('`')
```
result
```d
enum NOOP(a) = `a`;
enum BUG = `NOOP('`')`;
```

**Comment by Imperatorn** [comment]
> Minimal repro case
> 
> ```c
> #define NOOP(a) a
> #define BUG NOOP('`')
> ```
> 
> result
> 
> ```d
> enum NOOP(a) = `a`;
> enum BUG = `NOOP('`')`;
> ```

Correct :)
